Jan0707/phpstan-prophecy

- .gitattributes
- .travis.yml
- composer.json
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
First off, thanks for creating this extension, it works really well!!
I took the time to do some improvements:
* Updated composer.json
* all requirements are non-dev: those are the dependencies of this lib, they must be hard requirements! Otherwise I will be able to require this lib alongside (for example) PHPStan 0.8, and that will not work!
* PHPUnit requirement is relaxed to the whole 6 series: we're not using anything that requires a higher version, except PHPStan itself, which will handle it in its requirements
* PHPStan requirement is now `^0.9`, since we got it tagged! :tada: 
* Added `.gitattributes`: this reduces the number of files that are distributed with this lib through Composer
* Improved the Travis build:
* added PHP 7.2 :tada: 
* added a job to test with `--prefer-lowest` …
> Improve package

- src/extension.neon
`ProphecyMethodsClassReflectionExtension` does not implement the `PropertiesClassReflectionExtension` interface.
This fixes this extension, it was broken on my project.
> Fix extension definition

- composer.json
- composer.lock
After PHPUnit 7.0 is released, this change allows to use phpstan-prophecy in combination with phpunit ^7.0
> allow also to use phpunit 7.0

- .travis.yml
> Fix: Consistently indent with 4 spaces

- .travis.yml
> Fix: Use max level instead of 7

- .travis.yml
- composer.json
This PR
💁‍♂️ Running
```
$ composer validate
```
on current `master` yields
```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
```
❗️Also note that currently, license information is missing:
> Fix: Add description to composer.json

- composer.json
Since the license was added in 61facf7b6aa0328e800905ed1139240a5c7e4733, we should publish the same info on Packagist through this modification.
> Add license indication in composer.json

- .editorconfig
- .travis.yml
This PR
Follows https://github.com/Jan0707/phpstan-prophecy/pull/9#issuecomment-403722434.
💁‍♂️ For reference, see https://docs.travis-ci.com/user/build-stages/.
> Enhancement: Run tests against lowest, locked, and highest dependencies

- readme.md
This PR
💁‍♂️ For reference, see https://help.github.com/articles/creating-and-highlighting-code-blocks. 
Note that this also helps a lot when using PhpStorm:
> Enhancement: Trigger syntax highlighting in fenced code blocks

- readme.md
This PR
💁‍♂️ Also see https://github.com/Jan0707/phpstan-prophecy/releases.
> Fix: Remove invalid note about unavailability of release

- composer.json
PhpUnit 8 did not introduce any relevant breaking changes.
> Allow PhpUnit 8

- src/Type/ObjectProphecyType.php
cc @lcobucci @rdohms
I finally figured out what didn't work about the cache! It was using this method from a parent where `new self()` was used 🤦‍♂️
> Fixed restoration of ObjectProphecyType from cache

- src/Type/ObjectProphecyType.php
It fails with php 7.3, due to a missing import of PHPStan\Type\Type:
```
vendor/bin/phpstan analyze  -l 6
Note: Using configuration file /Users/swentz/git/mapper/phpstan.neon.
18/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  54%
Fatal error: Declaration of JanGregor\Prophecy\Type\ObjectProphecyType::__set_state(array $properties): JanGregor\Prophecy\Type\Type must be compatible with PHPStan\Type\ObjectType::__set_state(array $properties): PHPStan\Type\Type in /Users/swentz/git/mapper/vendor/jangregor/phpstan-prophecy/src/Type/ObjectProphecyType.php on line 43
```
> Add missing import to avoid fatal error with php 7.3

- src/PhpDoc/TypeNodeResolverExtension.php
This PR
Follows #31.
💁‍♂ This fixes the broken build. For reference, see https://travis-ci.org/Jan0707/phpstan-prophecy/builds/529313797.
> Fix: Run 'php-cs-fixer'

- .travis.yml
> Enhancement: Disable Xdebug as early as possible

- .travis.yml
This PR
Follows #18.
See https://travis-ci.org/Jan0707/phpstan-prophecy/builds/436194468:
See https://travis-ci.org/Jan0707/phpstan-prophecy/builds/446749712:
> Fix: Also run build with locked dependencies on PHP 7.1

- .travis.yml
- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/localheinz/composer-normalize.
> Enhancement: Normalize composer.json

- composer.json
- composer.lock
So that this extension can be managed through the brand new `extension-installer` from phpstan
> set package type to "phpstan-extension"

- .github/workflows/continuous-integration.yml
- CHANGELOG.md
- composer.json
- composer.lock
This PR
💁‍♂ A closer look at the tests reveal that the tests aren't important - they are only fixtures for running a static analysis using `phpstan`.
> Fix: Require at least phpstan/phpstan:^0.12.0

- .github/workflows/continuous-integration.yml
- composer.json
- composer.lock
> Enhancement: Use ergebnis/composer-normalize instead of localheinz/composer-normalize

- composer.json
- tests/Model/BaseModel.php
- tests/Test/BaseModelTest.php
> Fix: Namespace

- phpunit.xml
- tests/StaticAnalysis/Bar.php
- tests/StaticAnalysis/BaseModel.php
- tests/StaticAnalysis/BaseModelTest.php
- tests/StaticAnalysis/Baz.php
- tests/StaticAnalysis/Foo.php
> Enhancement: Move indirect tests into separate namespace

- composer.json
This PR
💁‍♂ These are already configured via `phpstan.neon`.
> Fix: Remove parameters

- .php_cs
- LICENSE
- composer.json
- composer.lock
> Enhancement: Use ergebnis/license

- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
> Fix: Do not import every single class

- CHANGELOG.md
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
This PR
💁‍♂ There's probably no reason to extend these classes.
> Fix: Mark classes as final

- CHANGELOG.md
- src/Reflection/ObjectProphecyMethodReflection.php
- tests/Unit/Reflection/ObjectProphecyMethodReflectionTest.php
This PR
Fixes #112.
💁‍♂ Does that make sense, @func0der?
> Fix: Method invocations on methods of ObjectProphecy might have side effects

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Allow installation with phpunit/phpunit:^9

- tests/StaticAnalysis/Src/Bar.php
- tests/StaticAnalysis/Src/BaseModel.php
- tests/StaticAnalysis/Src/Baz.php
- tests/StaticAnalysis/Src/Foo.php
- tests/StaticAnalysis/Test/BaseModelTest.php
> Fix: Move classes used in static analysis into different namespaces

- .github/CONTRIBUTING.md
- Makefile
- composer.json
> Enhancement: Use Makefile instead of composer scripts

- .editorconfig
> Fix: Configure indentation for Makefile

- .github/CONTRIBUTING.md
> Fix: Reference GitHub Actions instead of Travis CI

- .gitattributes
> Fix: Explicitly list ignored files and directories

- .gitattributes
- README.md
> Fix: Rename directory containing Dockerfile

- test/StaticAnalysis/Src/BaseModel.php
- test/StaticAnalysis/Test/BaseModelTest.php
- test/StaticAnalysis/Test/ProphesizeTest.php
- test/StaticAnalysis/Test/WillExtendTest.php
- test/StaticAnalysis/Test/WillImplementTest.php
> Fix: Split test cases used in static code analysis

- phpstan.neon
- test/StaticAnalysis/Test/ProphesizeTest.php
This PR
💁‍♂ The type should be resolved without a DocBlock.
> Fix: Type should be resolved without DocBlock

- test/StaticAnalysis/Test/WillImplementTest.php
> Enhancement: Add tests where willImplement() is used in setUp()

- test/StaticAnalysis/Test/WillExtendTest.php
> Enhancement: Add test where willExtend() is used in setUp()

- .github/workflows/continuous-integration.yml
- .gitignore
- .php_cs
- Makefile
- phpstan.neon
> Enhancement: Use .build directory for temporary files

- test/StaticAnalysis/Test/ObjectProphecy/ProphesizeTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillExtendTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillImplementTest.php
> Enhancement: Move tests into ObjectProphecy namespace

- test/StaticAnalysis/Test/ObjectProphecy/ProphesizeTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillExtendTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillImplementTest.php
> Fix: Rename test methods

- README.md
- phpstan.neon
- test/StaticAnalysis/Test/ObjectProphecy/ProphesizeTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillExtendTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillImplementTest.php
This PR
Related to #121.
💁‍♂ Does that make sense, @AnnaDam and @func0der? Note that this appears to work fine when not using return type declarations or DocBlocks.
> Enhancement: Add tests where prophesize(), willExtend(), and willImplement() are used in helper methods

- .github/workflows/integrate.yml
> Fix: Run static analysis with locked dependencies

- .github/workflows/integrate.yml
> Fix: Include phpunit/phpunit version in cache key

- README.md
> Fix: Add missing semicolon

- CHANGELOG.md
- README.md
- src/extension.neon
This PR
Related to https://github.com/Jan0707/phpstan-prophecy/issues/179#issuecomment-627177644.
> Fix: Remove symbolic link

- .github/workflows/triage.yaml
> Fix: Use appropriate secret

- .github/workflows/close.yaml
> Fix: Use pull_request_target

- .github/FUNDING.yml
- .github/actions/composer/composer/install/run.sh
- Makefile
> Enhancement: Synchronize with ergebnis/php-library-template

- .github/PULL_REQUEST_TEMPLATE.md
> Fix: Avoid use of acronyms

- CHANGELOG.md
- composer.json
- composer.lock
- phpstan-with-extension-baseline.neon
- phpstan-without-extension-baseline.neon
- src/Type/ObjectProphecy/WillExtendOrImplementDynamicReturnTypeExtension.php
- src/Type/Prophet/ProphesizeDynamicReturnTypeExtension.php
We are using this package in @sulu CMS and as phpstan 1.0 was released I thought it would be great to support the new phpstan version. This PR will set the required phpstan version to 1.0. Would I think be also a good time to tag also this package with 1.0 thats why I did not add it as additional allowed version.
> Add support for phpstan 1.0

- composer.json
- composer.lock
> Fix: Allow `ergebnis/composer-normalize` to run as `composer` plugin

- .github/workflows/integrate.yaml
> Fix: Expand matrix for `static-code-analysis` job

- phpstan-without-extension-baseline.neon
- src/Type/Prophet/ProphesizeDynamicReturnTypeExtension.php
- test/StaticAnalysis/Test/ObjectProphecy/ProphesizeTest.php
Closes https://github.com/Jan0707/phpstan-prophecy/issues/315
> Fix internal phpstan error

- phpstan-without-extension-baseline.neon
- test/StaticAnalysis/Test/ObjectProphecy/ProphesizeTest.php
Reverts only part of https://github.com/Jan0707/phpstan-prophecy/pull/316
Following test case produces different phpstan analyisis output depending on used versions:
```php
public function testCreateProphecyInline(): void
{
$prophecy = (new Prophet())->prophesize(Src\BaseModel::class);
$prophecy
->getFoo()
->willReturn('bar');
$prophecy
->doubleTheNumber(Argument::is(2))
->willReturn(5);
$testDouble = $prophecy->reveal();
self::assertEquals('bar', $testDouble->getFoo());
self::assertEquals(5, $testDouble->doubleTheNumber(2));
}
```
Creating Prophet inline seems like a valid use case that should be supported as well. In combination with PHPUnit 10.0.0. this produced internal phpstan error due to following [lines](https://github.com/Jan0707/phpstan-prophecy/pull/316/files#diff-4b3651c5d7ac20 …
> Remove problematic test case

- README.md
As I said at #347 , and changed like  
https://github.com/Jan0707/phpstan-prophecy/pull/348/commits/37d8420bb4ffde632761a655a876dd5884a4940e
It seems property `$prophecy` taken as `mixed` in phpstan. with level 10 would be error.
I removed it, because it is not mostly required as code example. 
Follows #348 
Related to #346
Fixes #348
> minimize README code example

- .github/workflows/integrate.yaml
- composer.json
- composer.lock
This pull request
This is a tentative PR to see if we can just widen the constraint, or if we need to do more work.
> Allow PHPUnit 12

- .github/workflows/integrate.yaml
- composer.json
- composer.lock
This reverts commit 5f940fa33510baa928af6518a152e5ab951ccfb2.
This pull request follows #364, needs the release of https://github.com/phpspec/prophecy-phpunit/pull/67 under a tag.
> Revert "Workaround to include phpspec/prophecy-phpunit#67"
