Jan0707/phpstan-prophecy

- composer.json
- composer.lock
> Fix: Require PHP 7.0

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.
> Enhancement: Keep packages sorted in composer.json

- .travis.yml
- composer.json
- composer.lock
This PR
Follows #20.
Blocks #26.
> Fix: Lock file is not up-to-date

- .gitignore
- .php_cs
- .travis.yml
- composer.json
- composer.lock
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/TestCaseProphesizeDynamicReturnTypeExtension.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- tests/Model/BaseModel.php
> Enhancement: Enforce PSR-2 with friendsofphp/php-cs-fixer

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/phpstan/phpstan/releases/tag/0.11.
> Enhancement: Allow installation of phpstan/phpstan:^0.11.0

- readme.md
The class that gets prophesized is called SomeModel not SomeClass
> Fixed wrong class name

- .github/CONTRIBUTING.md
- composer.json
- readme.md
> Enhancement: Add composer scripts for easily running development tools

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.13.1...v2.15.0.
> Enhancement: Update friendsofphp/php-cs-fixer

- composer.json
- composer.lock
- src/Reflection/ObjectProphecyMethodReflection.php
- tests/Model/BaseModel.php
- tests/Test/BaseModelTest.php
This PR
Fixes #69.
💁‍♂ For reference, see https://github.com/phpstan/phpstan/releases/tag/0.12.2.
> Enhancement: Allow installation with phpstan/phpstan:~0.12.2

- .github/workflows/continuous-integration.yml
> Fix: Reference

- .github/workflows/continuous-integration.yml
> Enhancement: Run builds on PHP 7.4

- CHANGELOG.md
- readme.md
> Enhancement: Add changelog

- .github/workflows/continuous-integration.yml
- phpstan.neon
> Enhancement: Configure level and paths via phpstan.neon

- tests/bootstrap.php
> Fix: Remove unused test bootstrap file

- phpunit.xml
> Fix: Configuration for phpunit

- .php_cs
> Fix: Inline variable

- .github/workflows/continuous-integration.yml
> Enhancement: Show version of phpstan/phpstan before running it

- README.md
> Enhancement: Add packagist badge

- .github/workflows/continuous-integration.yml
> Fix: Consistently quote strings in Yaml files

- .php_cs
- composer.json
- composer.lock
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
- tests/Test/BaseModelTest.php
> Enhancement: Use ergebnis/php-cs-fixer-config

- phpstan.neon
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
> Enhancement: Infer private property type from constructor

- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/Type/ObjectProphecyType.php
> Fix: Remove useless DocBlocks

- CHANGELOG.md
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillImplementDynamicReturnTypeExtension.php
- src/Type/ObjectProphecyType.php
- src/extension.neon
- tests/Model/Bar.php
- tests/Model/BaseModel.php
- tests/Model/Foo.php
- tests/Test/BaseModelTest.php
> Enhancement: Add support for willImplement()

- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
> Enhancement: Slightly clean up code

- CHANGELOG.md
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/Type/ObjectProphecyType.php
- src/extension.neon
- tests/Model/BaseModel.php
- tests/Model/Baz.php
- tests/Test/BaseModelTest.php
> Enhancement: Add support for willExtend()

- .php_cs
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
- tests/StaticAnalysis/BaseModel.php
- tests/StaticAnalysis/BaseModelTest.php
> Enhancement: Enable strict_types fixer

- .php_cs
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
- tests/StaticAnalysis/Bar.php
- tests/StaticAnalysis/BaseModel.php
- tests/StaticAnalysis/BaseModelTest.php
- tests/StaticAnalysis/Baz.php
- tests/StaticAnalysis/Foo.php
This PR
💁‍♂ What do you think, @Jan0707?
> Enhancement: Add file-level header

- phpunit.xml
- tests/Unit/Reflection/ObjectProphecyMethodReflectionTest.php
This PR
Slightly related to #112.
> Fix: Add missing test

- .github/workflows/continuous-integration.yml
This PR
💁‍♂ For reference, see https://github.com/shivammathur/setup-php/compare/1.6.0...1.8.2.
> Enhancement: Update shivammathur/setup-php

- .github/workflows/continuous-integration.yml
> Enhancement: Extract environment variable

- extension.neon
> Fix: Keep services sorted by name

- CHANGELOG.md
- src/Extension/ObjectProphecyRevealDynamicReturnTypeExtension.php
- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
- src/Extension/ProphetProphesizeDynamicReturnTypeExtension.php
- src/PhpDoc/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecyMethodReflection.php
- src/Reflection/ProphecyMethodsClassReflectionExtension.php
- src/Type/ObjectProphecyType.php
> Fix: Mark all classes as internal

- src/PhpDoc/TypeNodeResolverExtension.php
> Fix: Import parent namespace only

- .gitattributes
> Fix: Singular

- src/Extension/ObjectProphecyWillExtendOrImplementDynamicReturnTypeExtension.php
> Fix: Keep items sorted

- CHANGELOG.md
- extension.neon
- phpstan-without-extension-baseline.neon
- src/PhpDoc/ObjectProphecy/TypeNodeResolverExtension.php
- src/Reflection/ObjectProphecy/MethodReflection.php
- src/Reflection/ObjectProphecy/MethodsClassReflectionExtension.php
- src/Type/ObjectProphecy/ObjectProphecyType.php
- src/Type/ObjectProphecy/RevealDynamicReturnTypeExtension.php
- src/Type/ObjectProphecy/WillExtendOrImplementDynamicReturnTypeExtension.php
- src/Type/Prophet/ProphesizeDynamicReturnTypeExtension.php
- test/Unit/Reflection/ObjectProphecy/MethodReflectionTest.php
> Fix: Move and rename classes

- .github/workflows/integrate.yml
- README.md
> Fix: Rename workflow

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/ergebnis/license/compare/0.1.0...1.0.0.
> Enhancement: Require ergebnis/license:^1.0.0

- composer.json
- composer.lock
> Fix: Specify patch version as well

- .github/workflows/integrate.yml
> Enhancement: Run builds with different versions of phpunit/phpunit

- .github/workflows/integrate.yml
- composer.json
- composer.lock
> Enhancement: Run build with phpunit/phpunit:^8.0.0

- .github/workflows/integrate.yml
- Makefile
This PR
💁‍♂️ For reference, see https://github.com/composer/composer/commit/a0c5d519e985009fc6a50df03cffb6b886674ffa.
> Fix: Remove deprecated --no-suggest option

- .github/dependabot.yml
- composer.json
- composer.lock
This PR
💁‍♂ This probably requires to set up Dependabot and disable Violinist - is this something you would be up for, @Jan0707?
> Enhancement: Use dependabot

- .github/workflows/integrate.yml
> Enhancement: Automatically merge pull requests created by Dependabot

- .github/CONTRIBUTING.md
- .github/workflows/close.yaml
> Fix: Close pull requests opened by @violinist-bot

- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Allow installation with PHP 8.0

- .github/workflows/close.yaml
- .github/workflows/integrate.yaml
- .github/workflows/triage.yaml
> Fix: Adjust usage of octokit

- README.md
> Fix: Add badges

- src/Type/ObjectProphecy/WillExtendOrImplementDynamicReturnTypeExtension.php
> Fix: Split condition

- Makefile
This pull request
Extracted from #266.
> Fix: Path to baselines

- README.md
Copy-pasting doesn't work with it 
This pull request
Follows #.
Related to #.
Fixes #.
> Remove unnecessary `$`

- .github/workflows/integrate.yaml
> Fix: Do not bother creating directories

- .github/workflows/integrate.yaml
> Fix: Run tests on PHP 7.1

- .github/workflows/integrate.yaml
- composer.json
- composer.lock
> Fix: Configure platform in `composer.json`

- composer.json
- composer.lock
This pull request
Follows #.
Related to #.
Fixes #331
> Fix conflict version constraint

- composer.json
- composer.lock
Update composer normalize and fix composer normalize changes.
> Update composer normalize

- .php-cs-fixer.php
- test/Unit/Reflection/ObjectProphecy/MethodReflectionTest.php
Update php cs fixer to latest version
> Update php cs fixer to latest version

- test/StaticAnalysis/Test/ObjectProphecy/WillExtendTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillImplementTest.php
For more tests cases for https://github.com/Jan0707/phpstan-prophecy/pull/369
> Add more tests for willExtend and willImplement handling

- test/StaticAnalysis/Test/ObjectProphecy/WillExtendTest.php
- test/StaticAnalysis/Test/ObjectProphecy/WillImplementTest.php
https://github.com/Jan0707/phpstan-prophecy/pull/374
> Fix code style issues of https://github.com/Jan0707/phpstan-prophecy/pull/374

- composer.json
- composer.lock
See https://github.com/Jan0707/phpstan-prophecy/pull/369#issuecomment-2656606574
> Set correct requires phpstan version to 2-1-5
